### ISSUE TITLE
Storybookを導入する

### ISSUE THREAD

**Issue by keitakn** [nekochans/love-psychology-web#3]
# Doneの定義
- Storybookが利用出来る状態になっている事
- 現在存在するComponentに対応するストーリーファイルが作成されている事

# 補足情報
https://github.com/nekochans/portfolio-frontend/tree/master/.storybook を参照。

package.jsonも参照し `storybook` と名前が付いているpackageを全て追加する必要がある。

- 基本的に純粋な関数型ComponentのみにStoryファイルを追加すればOK
- Reduxが絡んでくるComponentは省略してOK

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは5くらいでいけると思う🐱！

ただしComponentが増えてきてからやると作成するストーリーファイルが多くなって5じゃ済まなくなりそう、あくまでも今の時点では5かなって感じだね！

**Comment by kobayashi-m42** [comment]
@keitakn なるほど！5で進めるね！
