### ISSUE TITLE
Reduxの実験用のカウンターアプリを作成する 

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/love-psychology-web#5]
# Doneの定義
- カウンターアプリがReduxを使用して実装されていること

 # 補足情報
Reduxの導入のために仮の機能を作成する

**Comment by kobayashi-m42** [comment]
@keitakn ストーリーポイントは8を想定しているよ🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！8で問題ないと思う🐱
